"""remove uuid

Revision ID: 251f66d44ccd
Revises: c765be347d21
Create Date: 2022-06-05 14:04:47.117746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251f66d44ccd'
down_revision = 'c765be347d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=False)
    op.create_index(op.f('ix_post_pic_id'), 'post_pic', ['id'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_post_pic_id'), table_name='post_pic')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    # ### end Alembic commands ###
