"""add email_otp table

Revision ID: 36bbf51ff4f0
Revises: 573440d98081
Create Date: 2022-05-31 17:06:40.915677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bbf51ff4f0'
down_revision = '573440d98081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otp',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('otp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_otp')
    # ### end Alembic commands ###
