"""add profile photo column in user

Revision ID: 3c6b4fc113bf
Revises: c52c3d265490
Create Date: 2022-05-22 18:05:22.834094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6b4fc113bf'
down_revision = 'c52c3d265490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.String(), server_default='images/user/default.jpg', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###
