"""otp column of email_otp converted into str

Revision ID: 54e79a06374c
Revises: 1289c5069c59
Create Date: 2022-06-01 23:34:12.524248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e79a06374c'
down_revision = '1289c5069c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
