"""add email_otp table

Revision ID: 573440d98081
Revises: 6855c099026f
Create Date: 2022-05-31 17:03:25.478071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573440d98081'
down_revision = '6855c099026f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
