"""remove profile pic table and add a column profile pic in users table

Revision ID: 77a1316999bd
Revises: f22b13b695cc
Create Date: 2022-05-27 23:35:33.012143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a1316999bd'
down_revision = 'f22b13b695cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
