"""remove profile pic table and add a column profile pic in users table

Revision ID: 77a1316999bd
Revises: f22b13b695cc
Create Date: 2022-05-27 23:35:33.012143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a1316999bd'
down_revision = 'f22b13b695cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_pic_id', table_name='profile_pic')
    op.drop_table('profile_pic')
    op.add_column('users', sa.Column('profile_pic', sa.String(), server_default='images/user/default.jpg', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    op.create_table('profile_pic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_photo', sa.VARCHAR(), server_default=sa.text("'images/user/default.jpg'::character varying"), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='profile_pic_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profile_pic_pkey')
    )
    op.create_index('ix_profile_pic_id', 'profile_pic', ['id'], unique=False)
    # ### end Alembic commands ###
