"""table id in uuid

Revision ID: c765be347d21
Revises: b2f244dd64e4
Create Date: 2022-06-05 13:47:41.486587

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c765be347d21'
down_revision = 'b2f244dd64e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
