"""remove pic column from posts and user table and make a separate table

Revision ID: e80f96abb965
Revises: 3c6b4fc113bf
Create Date: 2022-05-26 23:49:20.159444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80f96abb965'
down_revision = '3c6b4fc113bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.VARCHAR(), server_default=sa.text("'images/user/default.jpg'::character varying"), autoincrement=False, nullable=True))
     # ### end Alembic commands ###
