"""try to upgrade realtionship

Revision ID: f22b13b695cc
Revises: e80f96abb965
Create Date: 2022-05-27 09:04:26.798053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22b13b695cc'
down_revision = 'e80f96abb965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
